### ISSUE TITLE
Automate MALDI extraction pipeline

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/maldi-tools#15]
**Relevant background**

The MALDI pipeline currently involves much manual work on the user's end. Much of the pipeline can be automated to make the overall process more efficient.

**Design overview**

The components that can be automated are:

- [ ] Pre-extraction:
    - [x] Automatic generation of input masks for MALDI acquisition (#13): bypasses manual drawing around cores in FlexImaging. Frankie thinks better contrasting prior may mitigate issues with FlexImaging Magic Wand tool.
    - [x] Automatic `.imzml` and `.ibd` file generation (#14): bypasses SCiLS bottleneck, 5x faster using `timsconvert` CLI (supports normalization, if needed)
        - [ ] Combine spectra across multiple slides (timsconvert or matchms?)
    - [x] Ensure large `.imzml` files (about 1 TB) can be loaded using `pyimzml.ImzMLParser` (will most likely entail combining multiple `ImzMLParser` objects together)
- [ ] Extraction 
    - [ ] Restructure data directory to support extraction of multiple slides in MALDI notebook #16 
    - [ ] Ensure extracted signal per spot is done using area under the curve, not raw intensity
    - [ ] Glycan peaks (investigation)
        - [ ] Combine extracted glycan peaks between multiple slides (potentially [`matchms`](https://github.com/matchms/matchms)?)
        - [x] Identify correct peak for glycan in case of multiple matching
    - [ ] Integrate `spatialdata` and `napari` for visualizing the MALDI cohorts
- [ ] Post-extraction
    - [ ] Low-level clustering for masking out matrix regions outside the core (Cardinal, R package)
    - [x] Automatic identification of RNCM positions on TMA cores (#12):
        - [x] Use Albert tiler for naming (actual tiling already implemented, maybe code needed for generating input `.json` file)
        - [x] Use `.imzml` file to locate pixels on cores for cropping out
- [ ] Repo health
    - [ ] #17
    - [ ] #18
- [ ] Investigation
    - [ ] Slide-to-slide batch effects
    - [ ] Implement co-registration of MALDI images with HNE slides (`napari` plugin: [napari-imsmicrolink](https://github.com/nhpatterson/napari-imsmicrolink))

**Code mockup**

Please refer to the linked issues for more detail.

**Required inputs**

The same inputs will be needed.

**Output files**

The same output files will be produced.

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [ ] A week
- [X] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:

TBD

Estimated date when the finalized project will be merged in: 

TBD
